@startuml xcxv
start
:Channel?; <<procedure>>
repeat 
    :Get and Enter Channel;
    :Extract Verschraubung\nInformation; <<procedure>>
    #palegreen:INSERT INTO Verschraubung;
    :Enter into 'Last step';
    :Extract Step\nInformation; <<procedure>>

repeat while (Channels)


















stop


@enduml