@startuml xxxxxx
start
    #PaleTurquoise:Create Queries[];<<task>>
    :Extract Screwdrivers; <<load>>
    repeat
        :Select Screwdriver; <<input>>
        :Show Schraubfälle from\nselected Screwdriver; <<output>>
        :Select Action; <<input>>
        switch (Action)
            case ( Add )
                #PaleVioletRed:Create {Addition};
                :Enter Addition;  <<procedure>>
            case ( Edit ) 
                #PaleVioletRed:Create {Edition};
                :Select Schraubfälle; <<input>>
                :Enter Edition;  <<procedure>>
        endswitch
    repeat while (Confirm Changes)
    :Execute Queries; <<save>>
stop
@enduml