@startjson  MFV23_Halle101_11461CP
{ 
  "format": "channel",
  "result": "OK",
  "mac0": "00-C0-3A-6E-34-ec",
  "ip0": "10.52.97.94",
  "sw version": "2.500",
  "prg nr": 0,
  "prg name": "Vers. Schraube NG22",
  "prg date": "2022-05-27 13:11:48",
  "cycle": 109266,
  "date": "2025-04-11 07:50:17",
  "id code": "L 000000109266",
  "last step row": "4",
  "total time": "1.2",
  "tool serial": 206000001,
  "tightening steps": [
    {},{},{},{
      "row": "4",
      "name": "Schraubstufe",
      "result": "OK",
      "angle threshold": { "nom": 0, "act": -3.33 },
      "tightening functions": [
        {
          "name": "TF Angle",
          "nom": 3,
          "act": 6.21,
          "add": [{ "angle threshold": { "nom": 0, "act": -3.33 } }]
        },
        { "name": "MFs TimeMax", "nom": 10, "act": 0.18 }
      ],
      "graph": {
        "angle values": [1697.02, 1703.44, 1710.16],
        "torque values": [3.33, 3.33, 3.31],
        "time values": [0.7512, 0.7524, 0.7536]
      }
    }
  ]
}

@endjson
