@startjson MOE61_Halle206_BGGF1GF3
{
  "format": "channel",
  "result": "OK",
  "mac0": "00-C0-3A-6E-e7-52",
  "ip0": "10.52.116.38",
  "sw version": "2.500",
  "prg nr": 0,
  "prg name": "Abschlussdeckel_GF2_",
  "prg date": "2021-04-16 08:23:32",
  "date": "2025-04-10 07:24:12",
  "id code": "L 000000075617",
  "last step row": "4",
  "tool serial": 919000002,
  "tightening steps": [
    {},
    {
      "row": "4",
      "name": "Endanzug",
      "result": "OK",
      "tightening functions": [
        { "name": "TF Torque", "nom": 10.9, "act": 11 },
        { "name": "MFs TimeMax", "nom": 10, "act": 0.09 },
        { "name": "MF TorqueMin", "nom": 10.5, "act": 11 },
        { "name": "MF TorqueMax", "nom": 12, "act": 11 }
      ],
      "graph": {
        "angle values": [1285.8, 1287.87, 1289.42],
        "torque values": [8, 8.5, 8.81, 9.21],
        "time values": [0.8952, 0.8964, 0.8976]
      }
    }
  ]
}



@endjson