@startjson MFV23_Halle101_114227CP_recht
{
  "format": "channel",
  "result": "OK",
  "mac0": "00-C0-3A-6E-7a-33",
  "ip0": "10.52.97.93",
  "sw version": "2.500",
  "prg nr": 6,
  "prg name": "39Nm_DeckelNG25",
  "prg date": "2024-06-24 14:58:10",
  "cycle": 109266,
  "date": "2025-04-08 05:54:29",
  "id code": "L 000000223838",
  "last step row": "3",
  "tool serial": 519000003,
  "tightening steps": [
    {},
    {
      "row": "3",
      "name": "Endanzug",
      "result": "OK",
      "tightening functions": [
        { "name": "TF Torque", "nom": 38.7, "act": 38.86 },
        { "name": "MFs TimeMax", "nom": 10, "act": 0.18 },
        { "name": "MF TorqueMin", "nom": 34.58, "act": 38.86 },
        { "name": "MF TorqueMax", "nom": 41.42, "act": 38.86 }
      ],
      "graph": {
        "angle values": [2171.75, 2173.84, 2175.35],
        "torque values": [7.61, 3.89, 5.19, 3.44],
        "time values": [2.5608, 2.5908,2.616, 2.6364]
      }
    }
  ]
}
@endjson