@startuml xcxv
start
    :Create Verchraubung;
    if(Verschraubung['No of Channels']) then (> 1)
        :Extract from ID_Code\n'materialnummer' and\n'serialnummer';<<procedure>>
    else (1)
    endif
    :Get Screwdrivers ID; <<procedure>>

stop
@enduml