@startuml "Use Cases Messauftrag-Verwaltung"
left to right direction
skinparam actorStyle awesome

actor Fertigungsmitarbeiter as f
actor Messraummitarbeiter as m
actor Anwendungsbetreuer as a
actor Führungskraft as fk

usecase "Messauftrag Erstellen" as erstellen
usecase "Messauftrag Einsehen" as einsehen
usecase "Messauftrag Suchen" as suchen
usecase "Messauftrag Bearbeiten" as bearbeiten
usecase "Messauftrag Abschließen" as abschließen
usecase "Stammdatenpflege" as stammdatenflege
usecase "Priorisierung von Messaufträgen" as PVM

f --> erstellen
f --> einsehen
m --> einsehen
m --> suchen
m --> bearbeiten
fk --> bearbeiten
m --> abschließen
a --> stammdatenflege
bearbeiten --> PVM






@enduml

