@startuml "Messauftrag Suchen"
start
    :Create //Filters//;
    note right: {}
    repeat
        switch ("Filter nach...")
            case (Fertigungsauftragsnummer)
                :Enter **FAN**; <<input>>         

            case (Status)
                :Extract possible States; <<load>>

                :Show possible States; <<output>>

                :Select **possible State**; <<input>>

'            case (Spalte)
'                :Select column; <<input>>
'                    
'                if(Attribute) then (Category)
'                    :Show Values of Attributes; <<output>>
'
'                    :Select value; <<input>>
'                
'                else(NotCategory)
'                    :Enter value; <<input>>
'                                    
'                endif
'
'                :Add Value of Column to Filters; <<task>>
'
'            case (Datum)
'                :Enter Date From; <<input>>

'                :Enter Date To; <<input>>

'                :Validate that To > From; <<task>>
'
'                :Add Dates to Filters; <<task>>
'
            case(No filter)

        endswitch

                    
    repeat while (Search?)
    
    :Add Filters to Query; <<task>>

    :Extract Messaufträge with Filters; <<load>>

    :Show retreived Messaufträge; <<output>>

stop
@enduml