@startuml "Messauftrag Suchen"
start
    :Create Filters;
    repeat
        switch ("Filter nach...")
            case (Fertigungsauftragsnummer)
                :Enter FAN; <<input>>         

                :Add FAN to Filters{}; <<task>>

            case (Status)
                :Get Messaufträge with\n
            
                Bearbeitung = 'offen'; <<task>>
            
                if(Include Abgeschlossene?) then (yes)
                    :Get Messaufträge with\n
                    Bearbeitung = 'abgeschlossene'; <<task>>
            
                else (no)
                endif

                :Add Status to Filters; <<task>>

            case (Spalte)
                :Select column; <<input>>
                    
                if(Attribute) then (Category)
                    :Show Values of Attributes; <<output>>
                    :Select value; <<input>>
                else(NotCategory)
                    :Enter value; <<input>>
                                    
                endif

                :Add Value of Column to Filters; <<task>>

            case (Datum)
                :Enter Date From; <<input>>
                :Enter Date To; <<input>>
                :Validate that To > From; <<task>>

                :Add Dates to Filters; <<task>>

        endswitch

                    
    repeat while (Search?)
    
    :Add Filters to Query; <<task>>

    :Show Messaufträge with Filters; <<output>>

stop
@enduml