@startuml "Messauftrag erstellen"
start
    :Open Interface;
    
    fork
        :Get todays date; <<task>>
    fork again
        :Get User Data; <<task>>
    fork again
        :Create //Messafutrag//;
        note right: {}
    end fork

    :Enter **Fertigungsauftragsnummer**; <<input>>

    :Enter **Number of part to be checked**; <<input>>
    
    fork
        :Extract **Materialnummer**; <<load>>
    fork again
        :Extract **Materialtext**; <<load>>
    fork again
        :Extract **Arbeitsplatz**; <<load>>
    end fork

    :Display material number, text, workstation; <<output>>
    
    :Enter **Grund der Messung**; <<input>>

    :Select one or more **Form- und Oberflächenprüfung**; <<input>>


    if ("Other measuring task" selected?) then (yes)
        :Enter **description** text; <<input>>
    endif

    :Confirm;
 
    floating note right: All variables **in bold**\nwere added to //Messafutrag//

    :Save Messauftrag; <<save>>

    if(Add Begleitkarte?) then (yes)
        :Print Begleitkarte; 
        :Attach Begleitkarte;
    endif


stop
@enduml