@startuml "Messauftrag bearbeiten"
start
    :Show Messaufträge; <<output>>
    
    :Select Auftrag; <<input>>

    :Select action; <<input>>

    switch(action) 
    case (Location)
        :Show all Meassuring_Room; <<output>>

        :Select Meassuring_Room; <<input>>

        :Save new Meassuring_Room_History; <<save>>


    case (Status)
        :Extract Messaufgaben from Messauftrag; <<load>>

        :Show Messaufgaben; <<output>>

        repeat
            :Select Messaufgabe; <<input>>

        repeat while (Done selecting?)
        
        :Select State; <<input>>

        :Save new Task_State_History; <<save>>

        group 'Set proper State of Messauftrag'{
            :Set State = 0; <<task>>

            repeat
                :Read next step; <<load>>
                if (StepState == In Bearbeitung?) then (<color:green>yes)
                    :Set any = 1; <<task>>
                endif
        
            repeat while (More steps?)

            if (State) then (<color:green> 1)
                :Set State of Messauftrag to //In Bearbeitung//; <<save>>
            else(<color:red> 0)
                :Set State of Messauftrag to //Offen//; <<save>>
            endif
        
        }

    
    case (Priority)
        if(User Type) then(Führungskraft)
            :Show Priorities; <<output>>
            
            :Select priority; <<input>>

            :Save Priority_History; <<save>>

        else (Other)
            end
        endif

    endswitch

    :MessAufträge_Suchen; <<procedure>> 
    note right: just to show\nthe done changes.

stop
@enduml