@startuml "Schraubergebnisse einsehen"
start
    group 'Select Visualization'
        #Violet:Create {Visualization}; <<task>>
        note right: as Vis
        :Show Measurement; <<load>>
        :Select Measurement; <<input>>
        note: Vis.measurement
        repeat
            :Show Referenz_Typ; <<load>>
            note right: [Maximum, Minimum,\nNominal, Toleranz %]
            :Select Referenz_Typ; <<input>>
            note: Vis.referenz_typ
        repeat while (Done?)
    end group 
    :Verschraubungen Filtern; <<procedure>>
    group 'Show Referencing Lines'
        repeat
            :Extract Schraubfall_Sollwerte; <<load>>
        repeat while (Vis.referenz_typ) 
    end group
    :Show Visualization; <<output>>
stop
@enduml