@startjson MOE61_Halle207_BEM
{
  "format": "channel",
  "result": "OK",
  "mac0": "00-C0-3A-f0-ad-48",
  "ip0": "10.52.116.35",
  "sw version": "2.700",
  "prg nr": 1,
  "prg name": "Doppelabreisstopfen",
  "prg date": "2021-09-03 07:36:45",
  "cycle": 68112,
  "date": "2025-04-08 07:06:15",
  "id code": "L 000000068112",
  "last step row": "3",
  "tool serial": 78000003,
  "tightening steps": [
    {},
    {
      "row": "3",
      "name": "Endanzug",
      "result": "OK",
      "angle threshold": { "nom": 0, "act": 0.2 },
      "tightening functions": [
        {
          "name": "TF Angle",
          "nom": 1700,
          "act": 1702.12,
          "add": [{ "angle threshold": { "nom": 0, "act": 0.2 } }]
        },
        { "name": "MFs TimeMax", "nom": 20, "act": 2.61 }
      ],
      "graph": {
        "angle values": [360.21, 360.63, 362.14],
        "torque values": [0.2, 0.17, 0.24],
        "time values": [0.996, 0.9972, 1.0008]
      }
    }
  ]
}


@endjson